---
- name: Add bad directive under in Apache configuration
  hosts: webservers
  become: true
  ignore_errors: true
  
  tasks:
  
    - name: Pause for dramatic effect
      ansible.builtin.pause:
       prompt: "Pausing for dramtic effect - so you can see EDA"
       secounds: 5
  
    - name: Add InvalidDirectiveHere
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        insertafter: '^ServerRoot'  
        line: 'InvalidDirectiveHere'
        state: present
      tags:
        - never
        - break
      notify:
        - restart apache

    - name: Maintain httpd.conf
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^InvalidDirectiveHere$'
        state: absent
      tags:
        - never
        - restore
      notify:
        - restart apache

  handlers:
    - name: restart apache
      service:
        name: httpd
        state: restarted
