---
- name: Web app issue
  hosts: all
  sources:
   - ansible.eda.kafka:
       host: podman-rippley.demoredhat.com
       port: 9092
       topic: network

  rules:
   - name: http config issue
     condition: event.body.message is match("Failed to start The Apache HTTP Server.")
     action:
       run_job_template:
        organization: "Default"
        name: "Restore Web-Application"
