---
- name: Rulebook to print debug message based on webhook event
  hosts: testHost
  gather_facts: false

  sources:
      - ansible.eda.webhook:
          host: 0.0.0.0
          port: 5000

  rules:
      - name: Trigger update
        condition: 
          event.payload.server_name == 'node01'
        action:
         run_job_template:
          name: "Update RHEL"

      # - name: Trigger update
      #   condition: 
      #     event.payload.server_name == 'node02'
      #   action:
      #    run_job_template:
      #     name: update.yml

      # - name: Trigger update
      #   condition: 
      #     event.payload.server_name == 'node03'
      #   action:
      #    run_job_template:
      #     name: update.yml
          
           
