---
- name: Rulebook to print debug message based on webhook event
  hosts: all
  gather_facts: false

  sources:
      - ansible.eda.webhook:
          host: 0.0.0.0
          port: 5000

  rules:
    - name: Trigger update
      condition: event.payload.server_name == 'node01'
      action:
       run_job_template:
        organization: "Default"
        name: "Update RHEL"
        post_events: true
