---
- name: Rulebook to print debug message based on webhook event
  hosts: all
  gather_facts: false

  sources:
      - ansible.eda.webhook:
          host: 0.0.0.0
          port: 5000

  rules:
    - name: Service Now Ticket
      condition: event.payload.state == '1'
      action:
       debug:
