---
- name: Rulebook to print debug message based on webhook event
  hosts: testHost
  gather_facts: false

  sources:
      - ansible.eda.webhook:
          host: 0.0.0.0
          port: 6000

  rules:
      - name: Trigger update
        condition: event.payload.command == 'start'
        action:
         debug:
