---
- 
  name: Configure Windows Server as Domain Controller
  hosts: domain_controllers
  gather_facts: false

  vars_files:
    - windows_auth
  vars:
    wins_domain: "{{ ansible_interfaces[0].dns_domain }}"

  tasks:

   # - name: To view dns_domain from network segment
   #   ansible.builtin.debug:
   #    msg: "{{ ansible_interfaces[0].dns_domain }}"

   - name: Ensure local Administrator account has a password
     ansible.windows.win_user:
        name: "{{ username }}"
        password: "{{ user_password }}"

   - name: Promote system to a domain Controller
     microsoft.ad.domain:
      dns_domain_name: "{{ wins_domain }}"
      safe_mode_password: "{{ safe_password }}"
      domain_mode: Win2012R2
      forest_mode: Win2012R2
      reboot: true

   - name: Firewall rule to allow RDP on TCP port 5986
     win_firewall_rule:
      name: WinRM     
      localport: 5986
      action: allow
      direction: in
      protocol: tcp
      profiles: domain,private,public
      state: present
      enabled: yes        

